version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: politics_platform_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - politics_network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-politics_platform}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: politics_platform_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - politics_network
    depends_on:
      - app

  postgres:
    image: postgres:15-alpine
    container_name: politics_platform_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-politics_platform}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - politics_network

  redis:
    image: redis:7-alpine
    container_name: politics_platform_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - politics_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: politics_platform_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - politics_network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-politics_platform}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
      - app

networks:
  politics_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
